import os
import sys
import json
import ast
from pathlib import Path
from typing import Dict, Tuple, Any

from pipeline.context_loader import ContextLoader

def get_gemini_client():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ Error: GEMINI_API_KEY is not set.")
        sys.exit(1)
    
    from google import genai
    return genai.Client(api_key=api_key)

MODEL_NAME = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")

def check_python_syntax(files: Dict[str, str]) -> Dict[str, str]:
    """Verifies that all generated .py files have valid Python AST syntax."""
    errors = {}
    for path, code in files.items():
        if path.endswith(".py"):
            try:
                ast.parse(code)
            except SyntaxError as e:
                errors[path] = f"Line {e.lineno}: {e.msg}"
    return errors

def run_coder_agent(client, idea_title: str, idea_body: str, context: str) -> Dict[str, str]:
    """Agent 1 (Coder): Generates architecture, code files, and tests for the idea."""
    prompt = f"""
You are an expert Python software engineer building modular features for a hobby incubator.

Repository Context & Architecture Rules:
{context}

New Feature Request:
Title: {idea_title}
Description: {idea_body}

Task:
1. Implement this feature inside its own dedicated vertical slice under `src/features/<feature_name>/`.
2. Provide all needed files: `__init__.py`, `models.py`, `service.py`, and `cli.py` (which exposes `register_subcommand(subparsers)`).
3. Provide a unit test file under `tests/test_<feature_name>.py`.
4. Adhere strictly to the 150-line file limit.

Output Format:
Return a single, raw JSON object with the following schema:
{{
  "files": {{
    "src/features/<feature_name>/__init__.py": "...",
    "src/features/<feature_name>/models.py": "...",
    "src/features/<feature_name>/service.py": "...",
    "src/features/<feature_name>/cli.py": "...",
    "tests/test_<feature_name>.py": "..."
  }}
}}
Do NOT wrap your JSON in markdown fences (no ```json). Output pure JSON only.
"""
    from google.genai import types
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.2
        )
    )
    data = json.loads(response.text)
    return data.get("files", {})

def run_reviewer_agent(
    client, 
    idea_title: str, 
    generated_files: Dict[str, str], 
    syntax_errors: Dict[str, str]
) -> Tuple[Dict[str, str], str]:
    """Agent 2 (Reviewer): Fixes bugs/syntax, audits quality, and writes a PR summary."""
    files_json = json.dumps(generated_files, indent=2)
    errors_note = f"\nSyntax Errors Detected:\n{json.dumps(syntax_errors, indent=2)}" if syntax_errors else "\nNo initial AST syntax errors."

    prompt = f"""
You are a Senior Staff Engineer reviewing code generated by an AI assistant for the project: "{idea_title}".

Generated Files:
{files_json}
{errors_note}

Tasks:
1. Review code quality, correct any syntax errors, add missing imports, and fix potential bugs.
2. Ensure the feature satisfies the `register_subcommand(subparsers)` contract in its `cli.py`.
3. Provide a concise, professional Pull Request summary in GitHub Markdown.

Return raw JSON only:
{{
  "files": {{
    "path/to/file": "full code content"
  }},
  "review_summary": "### 🤖 Autonomous Agent PR Summary\\n\\n#### 🌟 What was built\\n- ...\\n\\n#### 🛠️ Files Added\\n- ...\\n\\n#### 🔍 Reviewer Fixes & Notes\\n- ..."
}}
"""
    from google.genai import types
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.1
        )
    )
    data = json.loads(response.text)
    return data.get("files", generated_files), data.get("review_summary", "Automated PR generated.")

def main():
    root = Path(__file__).resolve().parent.parent
    loader = ContextLoader(root)

    idea_title = os.environ.get("IDEA_TITLE", "CLI Habit Tracker")
    idea_body = os.environ.get("IDEA_BODY", "A command-line habit tracker with streak counting and JSON storage.")

    print(f"📦 Loading scoped context for: '{idea_title}'...")
    context = loader.assemble_targeted_context(idea_title, idea_body)

    client = get_gemini_client()

    print("🤖 [Coder Agent] Generating feature files...")
    files = run_coder_agent(client, idea_title, idea_body, context)

    syntax_errors = check_python_syntax(files)
    if syntax_errors:
        print(f"⚠️ Syntax errors caught before review: {syntax_errors}")
    else:
        print("✅ Initial syntax validation passed.")

    print("🧐 [Reviewer Agent] Auditing and producing final code...")
    final_files, review_summary = run_reviewer_agent(client, idea_title, files, syntax_errors)

    # Post-review syntax check
    post_syntax = check_python_syntax(final_files)
    if post_syntax:
        print(f"❌ Critical: Syntax error remaining after review: {post_syntax}")

    # Write files to disk
    print("💾 Writing feature files to repository...")
    for filepath, content in final_files.items():
        # Prevent overwriting critical pipeline / workflow files
        if filepath.startswith(".github/") or filepath.startswith("pipeline/"):
            print(f"⚠️ Skipping protected file: {filepath}")
            continue

        target_file = root / filepath
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(content, encoding="utf-8")
        print(f"  ✓ {filepath}")

    # Write PR summary for GitHub Action
    summary_file = root / "pr_summary.md"
    summary_file.write_text(review_summary, encoding="utf-8")
    print("📝 Written pr_summary.md")
    print("🎉 Pipeline run complete!")

if __name__ == "__main__":
    main()
